{% set name = "movement" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/movement-{{ version }}.tar.gz
  sha256: 17fe41bc380124eb43005821fb81bc7eb50f7e49184e06a60b0d33a261a49870

build:
  entry_points:
    - movement = movement.cli_entrypoint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10.0
    - numpy
    - pandas
    - h5py
    - attrs
    - pooch
    - tqdm
    - sleap-io
    - xarray
    - pyyaml
    - pytables
    - matplotlib-base
    - seaborn
    - nc-time-axis
    - scipy
    - bottleneck
    - numbagg
    - flox
    - opt_einsum

test:
  imports:
    - movement
  commands:
    - pip check
    - movement --help
    - movement info
  requires:
    - pip

about:
  home: https://movement.neuroinformatics.dev/
  summary: Analysis of body movement
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niksirbi
    - lochhh
    - adamltyson
